sudo: required
services:
  - docker

before_install:
  - docker build -f ./client/Dockerfile.dev -t omrikoss/client ./client

script:
  - docker run omrikoss/client npm test -- --coverage

after_success:
  - docker build -t omrikoss/client ./client
  - docker build -t omrikoss/nginx ./nginx
  - docker build -t omrikoss/server ./server
  - docker build -t omrikoss/worker ./worker
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker images
  - docker push omrikoss/client:latest
  - docker push omrikoss/nginx:latest
  - docker push omrikoss/server:latest
  - docker push omrikoss/worker:latest

deploy:
  provider: elasticbeanstalk
  region: us-east-2
  app: harman-multi-container
  env: HarmanMultiContainer-env
  bucket_name: elasticbeanstalk-us-east-2-243330637950
  bucket_path: harman-multi-container
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: "$AWS_SECRET_KEY"