sudo: required
services:
  - docker

before_install:
  - docker build -f ./client/Dockerfile.dev -t omrikoss/client ./client

script:
  - docker run omrikoss/client npm test -- --coverage

after_success:
  - docker build -t omrikoss/client ./client
  - docker build -t omrikoss/nginx ./nginx
  - docker build -t omrikoss/server ./server
  - docker build -t omrikoss/worker ./worker
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker images
  - docker push omrikoss/client:latest
  - docker push omrikoss/nginx:latest
  - docker push omrikoss/server:latest
  - docker push omrikoss/worker:latest